name: David's Home on the Web
description: Computational Biologist
url: https://www.kleinjdavid.com
baseurl: /blog
permalink: /:title/
version: v1.2.0

kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
